### ISSUE TITLE
TC0002: Interaction Handling with more than 1 federate

### ISSUE THREAD

**Issue by rhzg** [IVCTool/TS_HelloWorld#46]
in test case TC0002 the helloWorldBaseModel.getInteractionMessageStatus() must collect for all incoming interactions in order to test if SuT interaction has been received. Test in line 165 must be exteded to test a list of received messages

**Comment by ducana** [comment]
Changed handling of interactions to save interactions by country name. The tests will check if the values are correct for the country.
